# Project Metadata
version=0.3.0
maven_group=com.github.ssquadteam

# Toolchain
java_version=25

# Hytale Configuration
# 'release' or 'pre-release' - check your Hytale Launcher
patchline=pre-release

# Plugin Settings
includes_pack=false
load_user_mods=false

# Kotlin
kotlin.code.style=official

# Hytale Server API
hytale_server_version=0.6.0-pre.12.1
